# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161005_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book',
        ),
        migrations.AddField(
            model_name='buy',
            name='book_name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='buy',
            name='lang',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
