# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20161012_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
