# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpapers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques',
            old_name='ques',
            new_name='title',
        ),
    ]
