# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpapers', '0003_auto_20161005_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=140)),
                ('may_16', models.CharField(max_length=140)),
                ('dec_15', models.CharField(max_length=140)),
                ('may_15', models.CharField(max_length=140)),
                ('dec_14', models.CharField(max_length=140)),
                ('pdf_may_16', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='ques',
            name='subject',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sem',
            name='subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qpapers.ques'),
        ),
    ]
