# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpapers', '0004_auto_20161013_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem',
            name='pdf_dec_14',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sem',
            name='pdf_dec_15',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sem',
            name='pdf_may_15',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
