# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpapers', '0005_auto_20161013_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem',
            name='subj',
        ),
        migrations.AddField(
            model_name='ques',
            name='dec_14',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ques',
            name='dec_15',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ques',
            name='may_15',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ques',
            name='may_16',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ques',
            name='pdf_dec_14',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ques',
            name='pdf_dec_15',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ques',
            name='pdf_may_15',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ques',
            name='pdf_may_16',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ques',
            name='semester',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='sem',
        ),
    ]
